### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by gyanl** [gyanl/A-Color-A-Day#11]
Using keyboard shortcuts for generating a new random color, copying the current color, and copying all the colors. There are existing functions being called on the button clicks, they can be called on keypress. 

![artboard](https://cloud.githubusercontent.com/assets/9626697/19046990/9ba6ae30-89bd-11e6-8c2c-bf1a23e44efc.png)

**Comment by austinbenincasa** [comment]
I'll write a function that will do this for you.
