### ISSUE TITLE
copy from keyboard does not work

### ISSUE THREAD

**Issue by collnwalkr** [gyanl/A-Color-A-Day#15]
This [stackoverflow thread](http://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript) explains that a copy to the clipboard must be from a user. In other words, the current method for copying (invoking toast(color) ) is insufficient.

I have implemented a fix to this as well as added navigation between colors with the left and right arrow keys.

**Comment by collnwalkr** [comment]
#16

**Comment by gyanl** [comment]
Thanks @collnwalkr!
