### ISSUE TITLE
Using copy shortcut deselects color circle

### ISSUE THREAD

**Issue by gyanl** [gyanl/A-Color-A-Day#20]
Minor issue, but ideally circle should stay selected/enlarged.

**Comment by xyztdanid4** [comment]
I would like to work on this :)
Probably I will finish it today

**Comment by manu-chroma** [comment]
@xyztdanid4 Sure, go ahead! :)

**Comment by xyztdanid4** [comment]
fixed by https://github.com/gyanl/ChromaGen/pull/22
