### ISSUE TITLE
Create a gradient generator 

### ISSUE THREAD

**Issue by gyanl** [gyanl/A-Color-A-Day#21]
Should have : 
-A way to generate a gradient using two randomly generated colors (from first to second color)
-A rotate button to rotate the orientation of the gradient cyclically from right-->left to bottom-->top to left-->right to top-->bottom (can be done by changing the "to x" parameter in the CSS).
-A copy CSS button that copies the css code for the gradient in the format
background: #4DA0B0; /\* fallback for old browsers _/
background: -webkit-linear-gradient(to left, #4DA0B0 , #D39D38); /_ Chrome 10-25, Safari 5.1-6 _/
background: linear-gradient(to left, #4DA0B0 , #D39D38); /_ W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

**Comment by Niharika29** [comment]
Needs a hacktoberfest tag.

**Comment by manu-chroma** [comment]
I think @gyanl himself is working on the issue.

**Comment by gyanl** [comment]
Hey @Niharika29 - @violagupta is working on this but it's a little buggy right now, check gradient.html at https://github.com/ViolaGupta/ChromaGen
