### ISSUE TITLE
Improve gradient generator UI

### ISSUE THREAD

**Issue by gyanl** [gyanl/A-Color-A-Day#24]
Find a more elegant way to display gradients and maybe change the copy/copy all text to "CSS copied". Needs some thought.

**Comment by Niharika29** [comment]
Needs a hacktoberfest tag. :)

**Comment by gyanl** [comment]
@Niharika29 hahah okay :P

**Comment by Niharika29** [comment]
Great, I got this. @gyanl Could you explain how the gradient generator is supposed to work? Gradient between any random colors?

**Comment by gyanl** [comment]
The gradient + color generator is currently live : http://gyanl.github.io/ChromaGen/
You can generate both gradients and solid colors, and I think it might be better to move the functionalities to two separate pages - the index.html can have color generation, then there can be a link to the gradient generator page which has gradient generation only. 

A second issue is if you generate a gradient then the copy/copy all button shows an extremely long message which screws up the page, so for the gradient generator the text that's displayed on copying can be changed to "CSS copied" and "CSS copied for all" or something to that effect.

**Comment by gyanl** [comment]
Take a look at https://github.com/gyanl/ChromaGen/pull/23 for some history on the gradient generator

**Comment by eclecticexistential** [comment]
Greetings,

I would like to update the color generator.

**Comment by gyanl** [comment]
Thanks @eclecticexistential - closing this.
