### ISSUE TITLE
Switch between solid color and gradient generator.

### ISSUE THREAD

**Issue by gyanl** [gyanl/A-Color-A-Day#29]
Create UI to switch between solid color generator (currently index.html) and gradient generator (colorGradient.html)

**Comment by galczo5** [comment]
I can take it. One question, In index.html I see "Gradient" button, so do you expect similar switch in colorGradient.html? Or maybe you want to have gradient and solid color both in index.html with some kind of transition on change?

**Comment by gyanl** [comment]
@galczo5 Someone created the functionality for this - now we have a button to switch from solid to gradient and gradient to solid. If you can think of a better way to do it feel free to make something!

**Comment by galczo5** [comment]
Ok, I'll take it.

**Comment by galczo5** [comment]
Check this: https://github.com/gyanl/ChromaGen/pull/33

For me looks ok.

**Comment by gyanl** [comment]
Hey @galczo5 this seems to have broken the circle selection with the left and right arrow keys. Could you look into it?

**Comment by galczo5** [comment]
Yup. On my local branch https://github.com/galczo5/ChromaGen/tree/gradient-switch arrow selection works fine. 

In your version of script.js (https://github.com/gyanl/ChromaGen/blob/gh-pages/js/script.js#L114) I found line that doesn't appear in my code. I can prepare fix, but I don't know who and why put that line there. 

Git blame result: https://github.com/gyanl/ChromaGen/pull/32

**Comment by gyanl** [comment]
@galczo5 There have been a lot of contributors who have made small changes to the code, I'll try and clean it up a little soon. If you can submit a PR to fix it for now that'll be great. Thanks!

**Comment by galczo5** [comment]
Here https://github.com/gyanl/ChromaGen/pull/35

In prev PR I merged two html files into one, so I deleted colorGradient.html

**Comment by gyanl** [comment]
Thanks, closing this issue.
