### ISSUE TITLE
Improve Mobile layout

### ISSUE THREAD

**Issue by gyanl** [gyanl/A-Color-A-Day#30]
Make the page scrollable (issue arises when you generate a couple of gradients and then copy all - text goes out of the screen)

Also make the buttons and text fit inside the white rectangle - it's currently overflowing on mobile.

**Comment by srijitcoder** [comment]
I can work on this.

**Comment by srijitcoder** [comment]
Done look at #31

**Comment by gyanl** [comment]
Thanks @srijitcoder. Merged :)
