### ISSUE TITLE
Create a "Copy All" button

### ISSUE THREAD

**Issue by gyanl** [gyanl/A-Color-A-Day#4]
The copy all button should copy all of the currently generated hex codes, separated by spaces or commas.

**Comment by blackneck** [comment]
Hi, @gyanl 
By 

> all of the currently generated hex codes

do you mean those 6 which are visible or everything that user generate during session?

**Comment by gyanl** [comment]
@blackneck The currently visible 6.

**Comment by blackneck** [comment]
Thanks, @gyanl 
I also find that basic functionality is not working in my Safari on iOS and OS X

**Comment by Niharika29** [comment]
@blackneck It works on Safari for OS X for me. What OS X version are you using?

**Comment by blackneck** [comment]
@Niharika29 never mind, it suddenly start to work)

**Comment by gyanl** [comment]
Thanks @blackneck & @Niharika29 :)

**Comment by Niharika29** [comment]
My pleasure!
