### ISSUE TITLE
Create an option to use RGB or HSL instead of Hex codes.

### ISSUE THREAD

**Issue by gyanl** [gyanl/A-Color-A-Day#5]
Currently users can only copy the color as a hex code, but sometimes it's useful to have rgb or hsl values for web development work, so there could be a dropdown that allows you to change between modes. 

For eg. #0946f0 is equivalent to rgb(9, 70, 240) & hsl(224, 93%, 49%)

**Comment by manu-chroma** [comment]
Probably post a little mockup of how the drop-down list might appear on the page ?

**Comment by Niharika29** [comment]
Working on this.

**Comment by gyanl** [comment]
Resolved by #7
